### ISSUE TITLE
NetSuite - Token Based Auth

### ISSUE THREAD

**Issue by tayclark** [cloud-elements/devportal#1195]
## Description
* Verify Token Based Authentication is covered in all NetSuite 2016/v2 elements as shown for [NetSuite 2016 Human Capital](https://developers.cloud-elements.com/docs/elements/netsuite-2016-human-capital/setup.html?elementId=1688)

**Comment by davewilks** [comment]
All 2016 versions are covered, earlier versions are hidden.
