### ISSUE TITLE
Quickbooks Online curl sample url typo

### ISSUE THREAD

**Issue by lukevance** [cloud-elements/devportal#1242]
## Description
On the Authentication tab for the Quickbooks Online Element docs the example curl command is below:

![image](https://user-images.githubusercontent.com/13320316/30292017-cf47c354-96f1-11e7-9b35-e47344a5d0e6.png)

The portion of `/api-v2/elements/elements` should only be `/api-v2/elements`

**Comment by davewilks** [comment]
@lukevance Thanks for the catch. This is will be fixed in the next push.
