### ISSUE TITLE
Formula documentation for multipart and file upload/download requests

### ISSUE THREAD

**Issue by laurawyse** [cloud-elements/devportal#134]
Formula Builder docs should explain and show examples of the following:
1. How to download and upload a file
2. How to make a post request with a multipart body

Notes:
-Ask Laura for specifics on how this is actually done
-We may want to modify the way this is currently supported, so we should have a discussion about that before we document this. 

File download:
-normal GET request where the response will look like this:
```
{
        "filename": "myFile.pdf",
        "type": "workflow-file-attachment",
        "content": "base64 encoded string of file"
}
```
File upload:
-can use the body straight from a request that downloads the file. The request body should look like:
```
{
        "filename": "myFile.pdf",
        "type": "workflow-file-attachment",
        "content": "base64 encoded string of file"
}
```
Multipart Request:
-request body should be in this format:
```
{
    "parts": [
        {
            "name": "metaData",
            "content": {
                "your": "json"
            },
            "Content-Type": "text/plain"
        },
        {
            "name": "file",
            "filename": "myfile.jpg",
            "content": "the encoded string that you got when you downloaded the file",
            "Content-Type": "application/octet-stream"
        }
    ],
    "type": "workflow-multipart"
}
```

**Comment by jjwyse** [comment]
@laurawyse - since you know this best, can you just do this?
