### ISSUE TITLE
Cross reference the ServiceNow Basic and OAuth elements with each other

### ISSUE THREAD

**Issue by vineet-joshi** [cloud-elements/devportal#242]
## Description
If a customer/user is looking for ServiceNow OAuth and but ends up on the ServiceNow element page, it's would be a good user experience to add a link referencing the ServiceNow element from the ServiceNow OAuth element page and vice versa.

## Acceptance Criteria
1. A link pointing to the `ServiceNow OAuth` element documentation should exist on the `ServiceNow` element documentation page. The description/title for the link should be `Click here for OAuth based authentication for ServiceNow`.
1. A link pointing to the `ServiceNow` element documentation should exist on the `ServiceNow OAuth` element documentation page. The description/title for the link should be `Click here for Basic authentication for ServiceNow`

**Comment by vineet-joshi** [comment]
This issue was reported by Customer Success via https://github.com/cloud-elements/soba/issues/3522

**Comment by vineet-joshi** [comment]
@tclarkCO Will the above acceptance criteria satisfy the issue logged by Nintex? This is related to the ZH issue - https://github.com/cloud-elements/soba/issues/3522

**Comment by tclarkCO** [comment]
@vineet-joshi Perfect

**Comment by vineet-joshi** [comment]
@tclarkCO Thanks for reviewing.
