### ISSUE TITLE
Update Bulk for Prioritized Elements

### ISSUE THREAD

**Issue by tyler-cloud-elements** [cloud-elements/devportal#252]
## Description
As an integrator who wants to use Bulk, I want accurate documentation about bulk for the element that I am integrating.

**Comment by tyler-cloud-elements** [comment]
Oh actually this is all over the developer portal for bulk

**Comment by davewilks** [comment]
I think we'll need to refine this down to deal with the a priority list of elements.

**Comment by jimmacleodCE** [comment]
@davewilks You can de-prioritize Sage One and Save Live since we will deprecate these as Sage is building new elements.

**Comment by davewilks** [comment]
@daniel-cherry I think we should rename this and update the story. Maybe something like:
## Update Bulk for Prioritized Elements
As an integrator who wants to use Bulk, I want accurate documentation about bulk for the element that I am integrating.

This could also get linked to #382 and done at the same time.

**Comment by daniel-cherry** [comment]
https://developers.cloud-elements.com/docs/elements/sagelive/bulk.html

Lots of wrong info. here. Hub should be `sageaccounting`. Objects listed are marketing objects. Bulk csv example has the wrong field names.

**Comment by jimmacleodCE** [comment]
@daniel-cherry @davewilks This can be de-prioritized, we will be deprecating these elements as Sage is building new ones that will go into the Finance Hub

**Comment by davewilks** [comment]
@jimmacleodCE The reason we changed the title was so the issue addresses all priority elements, not Sage or other lower priority elements. We've basically turned it from a Sage-specific issue to a broader issue.

**Comment by jimmacleodCE** [comment]
Sweet!

**Comment by davewilks** [comment]
Duplicated by docathon
