### ISSUE TITLE
Quickbooks Enterprise: Invalid Poller Config

### ISSUE THREAD

**Issue by tyler-cloud-elements** [cloud-elements/devportal#256]
## Description
Looks like the Quickbooks Enterprise poller config has some strange characters in it `( '#{'$'})`, `        "url": "/hubs/finance/bills?where=TimeModified >= '#{'$'}{gmtDate:yyyy-MM-dd'T'HH:mm:ss'Z'}'",`

This should be corrected to match the poller found on the prod element

**Comment by daniel-cherry** [comment]
@davewilks did this tip get added to the QBD tips story that you finished last sprint?

**Comment by davewilks** [comment]
Closed with #766
