### ISSUE TITLE
Elements Builder: Resource Types

### ISSUE THREAD

**Issue by tayclark** [cloud-elements/devportal#269]
## Description
* Inspirato has requested we document (define) the various resource types allowed in Elements Builder
* Elements Builder -> Resources Tab -> Drop-down Resource Types

*[Zendesk Ticket](https://cloudelements.zendesk.com/agent/tickets/3218)

**Comment by davewilks** [comment]
@tclarkCO Anything specific? Can you give me some more info on this while updating the Element Builder?

**Comment by tclarkCO** [comment]
@davewilks - I'm thinking formal definitions of each resource type along w/ an example

**Comment by daniel-cherry** [comment]
@tclarkCO @davewilks Where are we wanting this info? Should this go in the "Tips" section for the insparato element?

**Comment by tclarkCO** [comment]
This should be part of the Resources documentation for Element Builder
