### ISSUE TITLE
Sage: Determine limitations of JacksonJsonUtils

### ISSUE THREAD

**Issue by travismcchesney** [cloud-elements/devportal#272]
@tyler-cloud-elements commented on [Wed Dec 07 2016](https://github.com/cloud-elements/soba/issues/3911)

## Description
We need to look into what characters are permissible for conversions. I think we use UTF-8 and it's causing problems with Sage who are using Unicode. Not necessarily a platform change or anything, but at least could use visibility on the developer portal. 

## Context
Sage is developing elements programmatically on WIndows boxes using Unicode. When they tried to import their custom element it broke the `convertStringToObject` parser in JacksonJsonUtils, due to the vast amount of hidden characters in the element json _(see at bottom)._ However, when they ran it through http://jsonlint.com/ validation and the RFC 7159 validator tool, it was fine (and when I ran the same thing - it was full of them).

## Steps to Reproduce
1. Download [SageLiveElementGenJsonV2 (1).txt](https://github.com/cloud-elements/soba/files/637776/SageLiveElementGenJsonV2.1.txt) (_see zip in comments for original_)
2. In Element Builder, import (1) using the Import Type: Element.
3. See "Failed to import to element builder format" in UI and parse errors in JacksonJsonUtils
4. In TextWranger, hit 'Zap Gremlins' which removes hidden/invisible characters (Text menu -> Zap Gremlins...)
5. Reimport and it's successful
---
## Notes
* Crazy hidden character images
<img width="1710" alt="img1-jsoneditor" src="https://cloud.githubusercontent.com/assets/13838430/20987197/5f3140c6-bc91-11e6-9dcd-14a363651159.png">
<img width="1033" alt="img2-textwrangler" src="https://cloud.githubusercontent.com/assets/13838430/20987200/60c24ff2-bc91-11e6-80e3-ba558f8d5f56.png">
<img width="1448" alt="screen shot 2016-12-05 at 11 00 12 pm" src="https://cloud.githubusercontent.com/assets/13838430/20987238/7ae337de-bc91-11e6-87b3-1813be3897cb.png">

---

@tyler-cloud-elements commented on [Thu Dec 08 2016](https://github.com/cloud-elements/soba/issues/3911#issuecomment-265871600)

For reference, I added the .txt for the extension to the previous file, but this is the specific zip file that they sent me

[SageLiveElementGenJsonV2 (1).zip](https://github.com/cloud-elements/soba/files/640713/SageLiveElementGenJsonV2.1.zip)

**Comment by davewilks** [comment]
I think this could be a quick fix by adding some content to Element Builder around importing.

**Comment by davewilks** [comment]
@travismcchesney and @tyler-cloud-elements I'm looking to add information about this to the Element Builder guide. Do you have any more details about what characters are not allowed? Would it work to just include a note when importing like:

When you import an element, make sure that the JSON is clean and does not include any hidden characters. Try running it through a JAON linter first or TextWranger.

**Comment by tyler-cloud-elements** [comment]
@davewilks Yeah - AFAIK I don't think we were able to dig further into what characters weren't permissible - perhaps @travismcchesney could elaborate. I think that general messaging would be appropriate 👍

**Comment by travismcchesney** [comment]
@davewilks I agree with @tyler-cloud-elements . Basically make sure it passes a JSON linter before trying to do an import.

**Comment by davewilks** [comment]
@travismcchesney and @tyler-cloud-elements Thanks for the input. I'll update the docs.
