### ISSUE TITLE
Twitter Polling Configuration

### ISSUE THREAD

**Issue by tclarkCO** [cloud-elements/devportal#294]
## Description
* Update Twitter events tab to point out that the polling configuration for `statuses` and `users` contains examples and will need to be edited before provisioning

![image](https://cloud.githubusercontent.com/assets/20074506/23713826/705296c6-03e4-11e7-913f-c06f3180d91a.png)

**Comment by davewilks** [comment]
@tclarkCO - what are you looking for here?

**Comment by tclarkCO** [comment]
@davewilks - Sorry I was pretty vague here. I'll research what I was doing and update the issue

**Comment by tclarkCO** [comment]
@davewilks - Updated the description
