### ISSUE TITLE
Element Tips: Salesforce

### ISSUE THREAD

**Issue by tclarkCO** [cloud-elements/devportal#314]
## Description
As a salesforce element user, I want to see specific detailed documentation so that I can implement a new instance with minimal input from Cloud Elements support.

* There is an issue where calls return `“INVALID_SESSION_ID – Session expired or invalid”` intermittently due to this setting being checked.
* We should add this to the FAQ or Additional Info for Salesforce since it is common 

![salesforcesettingsissue](https://cloud.githubusercontent.com/assets/20074506/22523800/e36415d6-e87d-11e6-92d1-765c94e03a3c.png)

**Comment by davewilks** [comment]
Zendesk tickets: 3164,3574

**Comment by cassiedbrown** [comment]
Looks good, I added one tip. @KelseyStevenson
