### ISSUE TITLE
Element Remediation: Shopify: Available Query Params

### ISSUE THREAD

**Issue by tayclark** [cloud-elements/devportal#315]
## Description
* Add documentation for available Shopify `/orders` query parameters in endpoint Swagger and/or Devportal
* https://help.shopify.com/api/reference/order#index
* Doesn't look like we support _all_ available params... From `ShopifyUtil.java`: 
>/**
     * Completes the query parameters for an Order search. Shopify only supports searching for a select number of
     * fields. These are entered as separate, specific query parameters instead of in a 'query'
     *
     * Note: we are currently passing in all of the search criteria as query parameters. Those which shopify supports
     * are used and those which it does not are just ignored in the search.
     * Shopify supports the following search criteria for each object:
     * -Orders: since_id, created_at_min, created_at_max, updated_at_min, updated_at_max, status, financial_status,
     * fulfillment_status, name
     * -Products: since_id, vendor, handle, product type, collection_id, created_at_min, created_at_max,
     * updated_at_min, updated_at_max, published_at_min, published_at_max, published_status, title
     * -Payments: since_id
     * @param params query parameters
     * @param elementQuery element query
     * @return query parameters
     */

**Comment by davewilks** [comment]
Adding to #401. This doesn't look like a quick fix.
