### ISSUE TITLE
Element Mapper: Endpoint to Object / Object to Endpoint

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#387]
As a user I should find a section in the Element Mapper (transformations guide) that explains endpoint to object and object to endpoint transformations

**Comment by daniel-cherry** [comment]
@claytonshaver does this story already exist here - https://developers.cloud-elements.com/docs/guides/element-mapper/advanced.html

**Comment by claytonshaver** [comment]
@daniel-cherry, I think you're right that the link above captures the story

**Comment by daniel-cherry** [comment]
closing as a duplicate
