### ISSUE TITLE
Formulas: FAQ / Tips

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#393]
As a user, I should find a formula user guide that contains a best practices section:

List of FAQs:
- [ ] Q: What is the current order that Formulas are returned in? 
A: The current order is by the Formula ID. 

- [ ] Q: Is there a maximum pageSize limit to the number of formulas returned?
A: Currently the max page size for Get formulas (and what you can see in the catalog) is 200.

**Comment by davewilks** [comment]
I think it'd take a couple of days to identify an initial list of FAQs and get those into the docs.
