### ISSUE TITLE
Formulas: Recover Lost Formulas

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#394]
As a user, I should find a formula user guide that explains how to recover lost or missing formulas

**Comment by rjmatt** [comment]
How would this happen?

**Comment by davewilks** [comment]
@rjmatt are you OK with us closing this issue? Nobody knows quite what it means.

**Comment by rjmatt** [comment]
Yeah -- let's close this.  We'll reopen if it comes up again.
