### ISSUE TITLE
Formulas: Triggers and Trigger Management

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#397]
As a user, I should find a formula user guide that contains a section on triggers and trigger management

**Comment by rjmatt** [comment]
One note for this:

Once you select a trigger for a formula, we do not currently allow you to change the Trigger type.  The reason for this is that there are code statements in specific steps that can reference the trigger (for example, trigger.body, trigger.request, etc).  If a user changes the Trigger type, suddenly the code in the formula that is looking at the trigger will fail, causing lots of confusion for users.

We will address this in a later revision of Formula Builder, but for now, we just disable the ability to change Trigger Type.
