### ISSUE TITLE
Integration Guide: Formulas

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#410]
As a cloud elements integrator, I should find formula creation instructions

**Comment by daniel-cherry** [comment]
@claytonshaver This is already complete correct?

**Comment by claytonshaver** [comment]
I think this issue is referring to breaking out the integration guide under get started by section

**Comment by daniel-cherry** [comment]
This is captured in the new integration guide. Formula guide content is captured in another story
