### ISSUE TITLE
Create new section in Formulas to cover Formula Steps

### ISSUE THREAD

**Issue by rjmatt** [cloud-elements/devportal#428]
## Description
Currently, in the Formula Docs, the description of each step is buried in the "Getting Started" section.  This makes it very difficult to find.  Let's create a new section called "Steps" to detail each step.

Additionally, we need to show UI screenshots of each step alongside the APIs.

**Comment by daniel-cherry** [comment]
- added formula retry explanation
- added formula element request stream
