### ISSUE TITLE
Elements Tips: Template and Research Top Elements

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#437]
## Description
Please put the description of the bug or feature here.

**Comment by davewilks** [comment]
In this sprint we identified the top elements based on number of tickets and based on additional user data provided by Jim. The results are stored in a spreadsheet at https://drive.google.com/open?id=1M1recWYDSDq6P2U8EfI3Ya6dm8C_vtAxJr-jRNZIi9A.

I will maintain this spreadsheet as more data comes in. The next steps are to continue working through the tips for the highest priority Elements, update the flow and structure of the Element docs, apply that updated structure to the priority elements, and then role that out to future elements.

For the next sprint, I'd like to update the organization and flow of the Element docs, apply that to the new elements that we will tackle, and then push that out to the prioritized list of elements.
