### ISSUE TITLE
Swiftpage_Shopify and Act essentials : Java script error for new orders .

### ISSUE THREAD

**Issue by padmajagade** [cloud-elements/devportal#443]
Description : #When an oder is created in shoppify and Woo commerce, Java script is failed to execute .
Re-steps :
1. Connect Shopify and Act essentials in the Elements connect.
2. Login to Shopify and create an order for the existing customer
3. Verify execution(#38271213) log CE console .
![Uploading Screen Shot 2017-02-27 at 12.02.39 PM.png…]()

Expected Results : Execute without any errors.
Actual Results : Java script failed to execute.

Note : Attached screenshot

**Comment by daniel-cherry** [comment]
@padmajagade Is this story created in the correct GitHub repository? This does not look like a documentation issue. If it is documentation specific, can you clarify what needs fixing?

**Comment by padmajagade** [comment]
Issue moved to [cloud-elements/formulas #203](https://github.com/cloud-elements/formulas/issues/203) via [**ZenHub**](https://www.zenhub.com/)
