### ISSUE TITLE
Swagger Docs: Ascent ERP: QuickBooks Enterprise /Products Post Update

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#459]
## Description
The QuickBooks Enterprise swagger documents need to be updated to reflect that we support all of the following /Product Post item types:

ItemSalesTax
ItemInventory
ItemNonInventory
ItemPayment
ItemOtherCharge
ItemService
SalesTaxCode
PaymentMethod
Currency
Account
Class
Terms

Currently, the documentation for POST /products in QB Enterprise reads as follows:

![11c37c20-ff2e-11e6-832c-af82c646de9f](https://cloud.githubusercontent.com/assets/25187684/23568164/9e62c3d2-0016-11e7-9afe-c72e9eda08d2.png)

**Comment by cassiedbrown** [comment]
@daniel-cherry will this also update the swagger within the console?

**Comment by daniel-cherry** [comment]
@atulbarve @greglindahl Do either of you know who can make these swagger documentation changes? This should be a relatively easy update if I can figure out who owns the element/swagger documentation for this element.

**Comment by daniel-cherry** [comment]
item types added to the code included all the items that are found in the .net code. There is a /currencies api that will have itemType as currency. 

Documentation changes were made and reviewed in - https://github.com/cloud-elements/soba/pull/5295

**Comment by daniel-cherry** [comment]
@cassiedbrown this issue has been completed in the above soba story. I am moving this to closed
