### ISSUE TITLE
HP: Update OneDrive GET /search parameter

### ISSUE THREAD

**Issue by tclarkCO** [cloud-elements/devportal#465]
## Description
* Add `isoDates` parameter to Swagger for `onedrivev2` & `onedrivebusiness` `GET /search` endpoint as seen on `GET /folders/contents`

**Comment by tclarkCO** [comment]
@daniel-cherry - Do you think it makes more sense to put Swagger documentation updates in `soba` since they may require testing?

**Comment by daniel-cherry** [comment]
@tclarkCO - I don't know what makes more sense. I am trying to sort out whether swagger update requests should live with the soba team. Hope to have more info on this soon and get this moved if needed

**Comment by daniel-cherry** [comment]
@greglindahl @atulbarve - Since doc team doesn't currently have access to make swagger updates, is this request something one of you can drive to complete?

**Comment by greglindahl** [comment]
@daniel-cherry This will need to get prioritized in the platform grooming meeting that happens every MWF at 1pm.  Do you go to that meeting? thanks

**Comment by daniel-cherry** [comment]
Issue moved to [cloud-elements/soba #5347](https://github.com/cloud-elements/soba/issues/5347) via [**ZenHub**](https://www.zenhub.com/)
