### ISSUE TITLE
Update tips for the top 10 Elements

### ISSUE THREAD

**Issue by davewilks** [cloud-elements/devportal#484]
## Description
As a Cloud Elements user, I would like to understand the quirks and element-specific information about the Element that I am integrating so I can more effectively create my integration.

Using the list at https://drive.google.com/open?id=1M1recWYDSDq6P2U8EfI3Ya6dm8C_vtAxJr-jRNZIi9A, update or create the tips section. To do so, have a brief meeting with those who know the most about the element. Think Atul, Caleb, Ramana, Tyler, support and answer:
* What are questions that we get (FAQs)?
* What are endpoint limitations that we know about?
* Are there any general tips about this element? Any quirks?

- [x] Salesforce CRM 
     - [x] #314 
     - [x] #321 - adding to #401 Epic to track with CEQL doc changes
     - [x] #447
- [x] MS Dynamics #451 
- [x] Marketo #453
- [x] Quickbooks Online & Enterprise 
     - [x] #452
     - [x] #256
- [x] Hubspot Marketing
     - [x] #362
     - [x] #316  
- [x] Dropbox
     - [x] #455
     - [x] #468
- [x] Shopify
     - [x] #454
     - [x] #320 -Added to #401
     - [x] #315  -Added to #401
- [x] Box #455
- [x] Netsuite CRM
     - [x] #456
     - [x] #466

**Comment by daniel-cherry** [comment]
@KelseyStevenson this and all corresponding stories in this epic are now complete correct?

**Comment by davewilks** [comment]
Closing as everything is either completed or added to another epic. I took a few of the not completed CEQL docs and added them to #401.
