### ISSUE TITLE
Welcome to Cloud Elements: Ross

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#492]
## Description
New document that goes through overview of sales discussion

**Comment by daniel-cherry** [comment]
@gssor Is this still an item on your radar? Should I move this down the priority list?

**Comment by gssor** [comment]
Still on my radar for sure. I'll get it done this sprint.

**Comment by daniel-cherry** [comment]
@gssor How is this coming along?

**Comment by daniel-cherry** [comment]
@gssor is this complete?

**Comment by daniel-cherry** [comment]
@davewilks ensure that glossary section of doc aligns with glossary in devportal

**Comment by daniel-cherry** [comment]
this issue has been reviewed and sync'd with marketing. Closing this out
