### ISSUE TITLE
SugarCRM_Developer Documentation Update

### ISSUE THREAD

**Issue by vineet-joshi** [cloud-elements/devportal#496]
@kristineim commented on [Fri Mar 17 2017](https://github.com/cloud-elements/soba/issues/5132)

## Description
IBM has requested that we update the developer documentation for SugarCRM to make it clear that the "oauth.callback.url" is an optional parameter and it would be helpful to add a description of this parameter. 

---

@kristineim commented on [Fri Mar 17 2017](https://github.com/cloud-elements/soba/issues/5132#issuecomment-287275241)

@claytonshaver is this something that would go to you?

**Comment by vineet-joshi** [comment]
@daniel-cherry Moved this issue from the product board to this board. Please let me know if it does not fit here. Thanks.

**Comment by davewilks** [comment]
@vineet-joshi Can you let me know what a good description of this parameter would be? "The URL of the page that you want to redirect to." "The URL of the page to return to after successful authentication."

**Comment by vineet-joshi** [comment]
@davewilks I think something like "The application URL to return to, after the authentication flow at SugarCRM has been completed" would work.
