### ISSUE TITLE
Netsuite Tip

### ISSUE THREAD

**Issue by cassiedbrown** [cloud-elements/devportal#540]
## Description
To post a value to a custom field, you must pass the data type along with the value of the field. For example, to post to a custom date field, you must pass the "ce_type" as "date". The following is an example:

```
{ 
"customFieldList": { 
"customField":[ 
{ 
          "scriptId": "custentity9",
         "ce_type":"date",
          "value": "2015-06-25T07:00:00Z"
} 
] 
}
```

**Comment by daniel-cherry** [comment]
close this as a dup
