### ISSUE TITLE
NetSuite Single Session Lock Configuration

### ISSUE THREAD

**Issue by tclarkCO** [cloud-elements/devportal#541]
## Description
* Update all NetSuite 2016 documentation to reflect Single Session Lock. These are required in the Create instance configuration to avoid issues. 
* The required fields are:
`"netsuite.single.session":"true"`
`"netsuite.single.session.key":"INSERT_KEY"`
*Recommendation for single session lock key from Atul:
>We recommend using your account_id & username for the Single Session Lock Key but users can use any value for this field. For our recommendation, if your account ID is 1234 and username is JohnSmith your Single Session Lock Key would be 1234JohnSmith. 
* Assignee should consult with Atul for any questions. It would probably be good to ask Atul what issues the Single Session Lock will help avoid in order to document the configuration correctly as we are still unclear if it is needed for all instances.

**Comment by daniel-cherry** [comment]
close this as notes are now added to #456
