### ISSUE TITLE
New Element: SAP C4C

### ISSUE THREAD

**Issue by KelseyStevenson** [cloud-elements/devportal#546]
## Description
Element documentation for new Element, SAP C4C

**Comment by KelseyStevenson** [comment]
Reference Soba #4463 

https://github.com/cloud-elements/soba/issues/4463

**Comment by tyler-cloud-elements** [comment]
For whoever picks this up, ping me and I can flesh out some more details

[C4C Tips.txt](https://github.com/cloud-elements/devportal/files/980323/C4C.Tips.txt) <- flow for enabling leads in a C4C tenant with pics and general element limitations/notes/tips
