### ISSUE TITLE
Salesforce: Webhook Setup

### ISSUE THREAD

**Issue by claytonshaver** [cloud-elements/devportal#555]
## Description
As a user I should be able to find information under Salesforce on how to set up webhooks for salesforce, including apex classes.

For some use cases webhooks should be discouraged since APEX classes will need to be added for every instance that is created since the APEX classes hard code the instance information. 
For single instance use cases (eg formula integration) webhooks can be used and are even recommended but for multiple instance use cases (customer's customers each needing webhooks) the webhook setup is a manual process and may prove to be a bad user experience. Additionally we should address this concern in the provisioning window so that users do not run all of their testing using webhooks only to find out their use case calls for polling.

**Comment by daniel-cherry** [comment]
Currently, the webhook documentation is incorrect and shows that you should set up your Remote Site Settings in Salesforce to include https://api.cloud-elements.com. However, for production it may also need to be https://console.cloud-elements.com

Also, if you are already updating your documentation, I noticed that the security verification was incorrect for the javascript version of the handling for the notification signature key. Just needed to throw a base64 encoding in there on the hex string. Might help out some people in the future!

// https://developers.cloud-elements.com/docs/guides/event-management/security.html 
var key = sjcl.codec.utf8String.toBits(notification_signature_key); 
var out = (new sjcl.misc.hmac(key, sjcl.hash.sha256)).mac(JSON.stringify(req.body)); 
var hex = sjcl.codec.hex.fromBits(out); 
var hmac = new Buffer(hex, 'hex').toString('base64’); // this line needs to be added :) 
// shaHeader == “sha256=“ + hmac

**Comment by tclarkCO** [comment]
@daniel-cherry - I'm creating another issue for the Security portion and will self-assign.

**Comment by tclarkCO** [comment]
@daniel-cherry I've added https://github.com/cloud-elements/devportal/issues/613 to address your last comment since we have a customer wanting to see this portion updated soon. 

@claytonshaver - I'm updating your description with some info regarding using webhooks for SFDC.

**Comment by tclarkCO** [comment]
Looks like the second portion of Clayton's description that I added is already there. Perhaps it should be written in *bold* and maybe include some information referring to use case issues the users may run into to make them more aware. 
![image](https://cloud.githubusercontent.com/assets/20074506/25498809/ffd86640-2b4e-11e7-8024-c36412076695.png)

**Comment by davewilks** [comment]
Lots of content has been added as a result of this issue. I just added a note at the top of the page and will address the idea of adding some content to the provisioning screen for Salesforce.
