### ISSUE TITLE
Elements Mapper getting started docs and advanced examples are mixed up

### ISSUE THREAD

**Issue by cgeene** [cloud-elements/devportal#563]
## Description
The documentation in Guides > Elements Mapper. All the titles for each doc is confusing and mixed up. For example Getting Started shows Advanced Javascript. Advanced Examples shows getting started

**Comment by davewilks** [comment]
@cgeene I'm working on this right now as part of #469.

**Comment by daniel-cherry** [comment]
@davewilks do you want me to close this as a dup?

**Comment by davewilks** [comment]
Keep it open. I added this to the epic which didn't have a specific ticket for this work. This will slot i nicely as the ticket for the checkbox at the bottom (Update C1 content as needed.)
