### ISSUE TITLE
The element instance PATCH API supports updating instance tags

### ISSUE THREAD

**Issue by vineet-joshi** [cloud-elements/devportal#567]
## Description
* Element instance tags could not previously be updated programmatically
* Now they can via the `PATCH /instances/{id}` API via the following type of payload
```
{
    "id": 764,
    ...
    "tags": [
    	"Test"    	
    ]
    ...  
}
```

With the above payload, any existing element instance tags will be deleted and the `Test` tag will be added to the element instance. In other words, for the sake of the tags, this is a `PUT` operation, although the overall API is a `PATCH` operation for the element instance.

**Comment by daniel-cherry** [comment]
@vineet-joshi Will this doc change need to be made under the swagger documentation?

**Comment by davewilks** [comment]
It looks like the model in the Swagger is updated to show this. It probably should be in the Element docs also. I think we should actually tag this with Element and add it to a sprint. It shouldn't take too long depending on the solution. Right now I'm thinking a note in the Create Instance section, which is easy to do, but time-consuming to update all of the Element docs.
