### ISSUE TITLE
Quickbooks; Configured application and endpoint setup documentation

### ISSUE THREAD

**Issue by KelseyStevenson** [cloud-elements/devportal#576]
## Description
As a Quickbooks user, I want documentation for configuring the application and setting up endpoints so that I can effectively provision an instance with NetSuite with minimal support. 

## Notes
As an output of the Quickbooks Element Tips meeting, it was observed that there is no documentation for configuring the application and setting up endpoints.

**Comment by davewilks** [comment]
Completed as part of docathon
