### ISSUE TITLE
Salesforce - Tip

### ISSUE THREAD

**Issue by tclarkCO** [cloud-elements/devportal#604]
## Description
* The Salesforce `base.url` can be specified during provisioning as part of your `configuration` object in your `POST /instances` payload. This can be used to authenticate an instance to a Salesforce Sandbox using https://test.salesforce.com. For this you will also need to set the siteAddress parameter on your call to `GET /oauth/url`

**Comment by cassiedbrown** [comment]
Provisioning for Sandbox accounts require the use of the https://test.salesforce.com. To specify this requirement in the OAUTH URL request, you can add an optional parameter called "siteAddress". See an example below:

https://console.cloud-elements.com/elements/api-v2/elements/sfdc/oauth/url?apiKey=<key>&apiSecret=<secret>&callbackUrl=https://console.cloud-elements.com/elements/jsp/home.jsp&siteAddress=https://test.salesforce.com
