### ISSUE TITLE
Epic - Element Cleanup: Top 10

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#615]
## Description
In this epic we will remediate/verify that existing documentation is not generically applied to all elements. The verification priority is Authentication, Events and Transform Data with the remaining categories as a secondary priority: endpoint setup, create instance, bulk, error code, and querying. 

### Stories
- [x] Salesforce #616 
- [x] Microsoft Dynamics CRM #617 
- [x] HubSport Marketing #618 
- [x] QuickBooks Online #619 
- [x] QuickBooks Desktop #620 
- [x] NetSuite Finance 2016 #621 
- [x] Marketo #622 
- [x] Zendesk #623 
- [x] Shopify #624 
- [x] Box #625

**Comment by davewilks** [comment]
Closing as most issues were either already closed or duplicates of docathon work, most of which is complete for these elements.
