### ISSUE TITLE
Element Cleanup: Microsoft Dynamics CRM

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#617]
## Description
As a Microsoft Dynamics CRM element user, I want to see documentation specific to the Microsoft Dynamics CRM element for:

* Authentication
* Events and Transform Data
* Endpoint setup
* Create instance
* Bulk
* Error code
* Querying

**Comment by cassiedbrown** [comment]
Add support info:
As of 5/5/2017 - We support 2013 - 2015 editions of Microsoft Dynamics with major support for the 2016 version.
