### ISSUE TITLE
Element Cleanup: NetSuite Finance 2016

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#621]
## Description
As a NetSuite Finance 2016 element user, I want to see documentation specific to the NetSuite Finance 2016 element for:

* Authentication
* Events and Transform Data
* Endpoint setup
* Create instance
* Bulk
* Error code
* Querying

**Comment by cassiedbrown** [comment]
For querying:  tranId can be used to query using the form of both SLS00000170 or 170. If you try this out with 0170, 17, 00000170, or SLS0000017 you will see that it returns a proper response(empty array).
