### ISSUE TITLE
Element Tip: Oracle Service Cloud

### ISSUE THREAD

**Issue by KelseyStevenson** [cloud-elements/devportal#661]
## Description

https://github.com/cloud-elements/soba/issues/5556

Element name : Oracle Service Cloud

Facing Error "This endpoint does not support retrieving/creating this object" for the following resources mentioned in below bugs,
#4682 , #4683 , #4684 and #4685

GET /incidents/{id}/attachments
PUT /incidents/{id}/attachments
GET /incidents/{id}/attachments/{attachmentId}
DELETE /incidents/{id}/attachments/{attachmentId}
GET /incidents/{incidentId}/comments/{commentId}
DELETE /incidents/{incidentId}/comments/{commentId}
GET /incidents/{incidentid}/Comments/{commentid}
GET /attachments
POST /attachments
GET /attachments/{id}
DELETE /attachments/{id}
GET /priorities
POST /priorities
GET /priorities/{id}
DELETE /priorities/{id}
PATCH /priorities/{id}
GET /statuses
POST /statuses
GET /statuses/{id}
DELETE /statuses/{id}
PATCH /statuses/{id}

**Comment by KelseyStevenson** [comment]
Note: These APIs are supported by the Hub, but are not supported by the element

**Comment by KelseyStevenson** [comment]
Decision to document in CS Wiki for internal purposes and FYI. APIs were removed from the swagger #5555 and adding additional information about them could further complicate the Customer User experience. 

Assigning to Cassie to document in Wiki.

**Comment by daniel-cherry** [comment]
@cassiedbrown can you provide an update on this?
