### ISSUE TITLE
Add Netsuite Finance Tips

### ISSUE THREAD

**Issue by KelseyStevenson** [cloud-elements/devportal#671]
## Description
The following tips should be added to Netsuite Finance Element.

- There are 10 different types of `items` in Netsuite Finance. When you `GET /Items/{id}`, the payload will have an _objType that you can use to define the type of item. You need the type of item to create an /Items/{id}

- Accounts in Finance = Ledger Accounts

**Comment by cassiedbrown** [comment]
New tip for ALL of netsuite:

How to query by internal ids and differentiate between them?
To search by the entity internal Id, your where clause would be like this

`entity=11769`

If you wanted to search by some other internalID, say for salesRep for example. You would have your where clause like this:

`salesRep=36`
