### ISSUE TITLE
The where clause documentation for the QBO element's /reports/{id} API is inaccurate

### ISSUE THREAD

**Issue by vineet-joshi** [cloud-elements/devportal#698]
## Description
The documentation for the `where` parameter for the `GET /reports/{id}` API for the QBO element is not aligned with the element code, which in turn is not aligned with the QBO API/SDK code.

For example the QBO API supports a filter called `dateMacro`, which is represented in the QBO element as `dateRange`, but the documentation has `predefinedDateRange`. Using `dateMacro` or `predefinedDateRange` does NOT work, but `dateRange` does work with the element.

The documentation needs to be updated to represent what the element supports. This might need digging in the the QBO element's code, so please seek help from someone in engineering for the same.

**Comment by tclarkCO** [comment]
@vineet-joshi - 
Would you like us to change the code to acknowledge `predefinedDateRange` or just change the Swagger to reflect the parameter as it is currently accessible in the code `dateRange`?
