### ISSUE TITLE
Docathon Prep - Tasks

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#699]
## Description

- [x] Create epic for each platinum element organized by priority that contains the following:
   - [x] CEQL
   - [x] Authenticate
   - [x] Events
   - [x] Bulk
   - [x] Endpoint Setup
   - [x] Overview
- [x] Finish style guide and add link
- [x] Detailed instructions (pick up stories, and how to work through them to complete the story and mark it done)
- [x] Invite Dallas team to slack, get time commitment from them, etc...
- [x] Make reservation at Atomic Cowboy
- [x] acquire budget for event
- [x] send out meeting invites for required attendees
- [x] identify prizes and how we will track completed stories

**Comment by davewilks** [comment]
I finished my portions of this, I think we can close it down!
