### ISSUE TITLE
Docathon - NetSuite Finance 2016 - CEQL

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#714]
## Description
Update CEQL docs to reflect all known limitations, expectations, and best practices

**Comment by KelseyStevenson** [comment]
Limitation to document: 

New tip for ALL of netsuite:

How to query by internal ids and differentiate between them?
To search by the entity internal Id, your where clause would be like this

entity=11769

If you wanted to search by some other internalID, say for salesRep for example. You would have your where clause like this:

salesRep=36
