### ISSUE TITLE
Docs Search: Salesforce CRM not found

### ISSUE THREAD

**Issue by tclarkCO** [cloud-elements/devportal#878]
## Description
* When searching for Salesforce or Salesforce CRM in the global search Salesforce CRM pages are not presented

![image](https://cloud.githubusercontent.com/assets/20074506/26764869/4ddedc76-4935-11e7-8147-9d3b4d01808b.png)

**Comment by davewilks** [comment]
Per a request from Jim, we changed the name to Salesforce Sales Cloud to align with how it is branded.

**Comment by tclarkCO** [comment]
Sounds good. I'll raise a PR to rename this in the catalog. Thanks !
