### ISSUE TITLE
Import element names from soba

### ISSUE THREAD

**Issue by tclarkCO** [cloud-elements/devportal#944]
## Description
* To keep names consistent across docs we should investigate feasibility of importing element names by element key when they are mentioned
* Possible solutions:
  * Syncing `devportal` weekly with `soba` element names
  * Importing via `GET /elements` API call during doc rendering
  * ....

**Comment by tclarkCO** [comment]
Putting on-hold until discussing long-term plans for documentation maintenance w/ @jasond-ce

**Comment by jasond-ce** [comment]
Thanks - I'll setup a meeting with you to try to understand this a little better.

**Comment by tclarkCO** [comment]
Closing since we'll be migrating docs to EB eventually and effort for this doesn't make sense at the moment.
